language: python
dist: xenial
python:
  - "3.6"
script:
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
addons:
  apt:
    packages:
      - libgdal-dev
      - libsqlite3-mod-spatialite

