# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-04 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0005_auto_20160509_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchrow',
            options={},
        ),
    ]
