# Generated by Django 2.2.13 on 2020-06-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0008_auto_20200107_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrow',
            name='medium_description',
            field=models.TextField(blank=True, null=True, verbose_name='Evidence Description'),
        ),
    ]
