# Generated by Django 2.2.16 on 2020-10-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0009_batchrow_medium_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchrow',
            name='book_copy_call_number',
            field=models.CharField(blank=True, help_text='This call number is identified with a different BHB number ', max_length=256, null=True, verbose_name='Book Copy Call Number'),
        ),
    ]
