# Generated by Django 4.2.16 on 2024-11-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0010_auto_20201013_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrow',
            name='imprint_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Imprint Notes'),
        ),
    ]
