# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-14 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20160503_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='footprint',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
