# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-06 17:11
from __future__ import unicode_literals

from django.db import migrations

batch_permissions = [
    'add_batchjob', 'change_batchjob', 'delete_batchjob',
    'add_batchrow', 'change_batchrow', 'delete_batchrow'
]

main_create_edit_permissions = [
    'add_role', 'change_role',
    'add_language', 'change_language',
    'add_digitalformat', 'change_digitalformat',
    'add_digitalobject', 'change_digitalobject',
    'add_standardizedidentification', 'change_standardizedidentification',
    'add_person', 'change_person',
    'add_place', 'change_place',
    'add_collection', 'change_collection',
    'add_writtenwork', 'change_writtenwork',
    'add_imprint', 'change_imprint',
    'add_bookcopy', 'change_bookcopy',
    'add_footprint', 'change_footprint',
    'add_actor', 'change_actor',
    'add_standardizedidentificationtype',
    'change_standardizedidentificationtype',
    'add_extendeddate', 'change_extendeddate'
]

main_delete_permissions = [
    'delete_role', 'delete_language', 'delete_digitalobject',
    'delete_standardizedidentification', 'delete_person',
    'delete_place', 'delete_collection', 'delete_writtenwork',
    'delete_imprint', 'delete_bookcopy', 'delete_footprint',
    'delete_actor', 'delete_standardizedidentificationtype',
    'delete_extendeddate'
]


def add_permissions(Permission, group, names):
    lst = list(Permission.objects.filter(codename__in=names))
    group.permissions.add(*lst)


def create_group_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    Footprint = apps.get_model('main', 'Footprint')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    content_type = ContentType.objects.get_for_model(Footprint)
    moderation_permission, created = \
        Permission.objects.get_or_create(codename='can_moderate',
                                         name='Can Moderate',
                                         content_type=content_type)

    group = Group.objects.create(name='SuperModerator')
    group.permissions.add(moderation_permission)
    names = (batch_permissions + main_create_edit_permissions +
             main_delete_permissions + ['change_user'])
    add_permissions(Permission, group, names)

    group = Group.objects.create(name='Moderator')
    group.permissions.add(moderation_permission)
    add_permissions(Permission, group, main_create_edit_permissions)

    group = Group.objects.create(name='Contributor')
    add_permissions(Permission, group, main_create_edit_permissions)

    group = Group.objects.create(name='Creator')
    add_permissions(Permission, group, main_create_edit_permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20170306_1145'),
    ]

    operations = [
        migrations.RunPython(create_group_roles),
    ]
