# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20170307_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writtenwork',
            name='title',
            field=models.TextField(null=True, unique=True),
        ),
    ]
