# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-25 18:08
from __future__ import unicode_literals

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20170309_1224'),
    ]

    operations = [
        CreateExtension('postgis'),
    ]
