# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-25 18:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20170425_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latlng',
            field=django.contrib.gis.db.models.fields.PointField(
                null=True, srid=4326),
        ),
    ]
