# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-27 15:52
from __future__ import unicode_literals

from django.contrib.gis.geos.point import Point
from django.db import migrations


def migrate_geoposition(apps, schema_editor):
    Place = apps.get_model('main', 'Place')
    for p in Place.objects.all():
        p.latlng = Point(
            float(p.position.longitude), float(p.position.latitude))
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_place_latlng'),
    ]

    operations = [
        migrations.RunPython(migrate_geoposition),
    ]
