# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-27 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20170427_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='position',
        ),
    ]
