# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_place_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['country', 'city', 'id'],
                     'verbose_name': 'Place'},
        ),
        migrations.AddField(
            model_name='footprint',
            name='verified_modified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
