# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 16:04
from __future__ import unicode_literals

from django.db import migrations


def backfill_verified_date(apps, schema_editor):
    Footprint = apps.get_model('main', 'Footprint')
    for fp in Footprint.objects.filter(verified=True):
        fp.verified_modified_at = fp.modified_at
        fp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20170911_1014'),
    ]

    operations = [
         migrations.RunPython(backfill_verified_date),
    ]
