# Generated by Django 2.2.9 on 2020-01-07 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20191204_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalobject',
            name='file',
            field=models.FileField(upload_to='%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='actor',
            field=models.ManyToManyField(blank=True, help_text='An owner or other person related to this footprint. ', to='main.Actor'),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='associated_date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ExtendedDate', verbose_name='Footprint Date'),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='medium',
            field=models.CharField(help_text="Where the footprint is derived or deduced from, e.g.\n            an extant copy with an owner's signature", max_length=256, verbose_name='Evidence Type'),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Place', verbose_name='Footprint Location'),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='provenance',
            field=models.TextField(help_text='Where can one find the evidence now: a particular\n        library, archive, a printed book, a journal article etc.', verbose_name='Evidence Location'),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Footprint Title'),
        ),
        migrations.AlterField(
            model_name='imprint',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Imprint Title'),
        ),
        migrations.AlterField(
            model_name='role',
            name='level',
            field=models.CharField(choices=[('footprint', 'Footprint'), ('imprint', 'Imprint'), ('writtenwork', 'WrittenWork'), ('place', 'Place'), ('person', 'Person')], max_length=25),
        ),
        migrations.AlterField(
            model_name='standardizedidentificationtype',
            name='level',
            field=models.CharField(choices=[('footprint', 'Footprint'), ('imprint', 'Imprint'), ('writtenwork', 'WrittenWork'), ('place', 'Place'), ('person', 'Person')], max_length=25),
        ),
        migrations.AlterField(
            model_name='writtenwork',
            name='actor',
            field=models.ManyToManyField(blank=True, help_text='The author or creator of the work. ', to='main.Actor'),
        ),
    ]
