# Generated by Django 2.2.12 on 2020-04-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20200107_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['alternate_name', 'canonical_name', 'id'], 'verbose_name': 'Place'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='digital_object',
        ),
        migrations.RemoveField(
            model_name='place',
            name='notes',
        ),
        migrations.AddField(
            model_name='place',
            name='alternate_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='canonical_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
