# Generated by Django 2.2.12 on 2020-04-21 14:16

import audit_log.models.fields
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0040_auto_20200418_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='standardized_identification',
        ),
        migrations.CreateModel(
            name='CanonicalPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.TextField()),
                ('latlng', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('geoname_id', models.TextField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='can_place_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='can_place_last_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canonical Place',
                'ordering': ['canonical_name', 'id'],
                'unique_together': {('canonical_name', 'latlng')},
            },
        ),
        migrations.AddField(
            model_name='place',
            name='canonical_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CanonicalPlace'),
        ),
    ]
