# Generated by Django 2.2.12 on 2020-04-21 17:13

from django.db import migrations


def migrate_to_canonical_place(apps, schema_editor):
    CanonicalPlace = apps.get_model('main', 'CanonicalPlace')
    Place = apps.get_model('main', 'Place')
    for place in Place.objects.all():
        place.canonical_place, created = CanonicalPlace.objects.get_or_create(
            latlng=place.latlng,
            canonical_name=place.canonical_name)
        place.save()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('main', '0041_auto_20200421_1016'),
    ]

    operations = [
        migrations.RunPython(migrate_to_canonical_place),
    ]
