# Generated by Django 2.2.12 on 2020-04-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20200421_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['alternate_name', 'canonical_place__canonical_name', 'id'], 'verbose_name': 'Place'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='canonical_name',
        ),
        migrations.RemoveField(
            model_name='place',
            name='latlng',
        ),
    ]
