# Generated by Django 2.2.13 on 2020-06-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20200421_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footprint',
            name='medium_description',
            field=models.TextField(blank=True, null=True, verbose_name='Evidence Description'),
        ),
    ]
