# Generated by Django 2.2.15 on 2020-08-21 14:07

from django.db import migrations


def cleanup_standardized_identifiers(apps, schema_editor):
    StandardizedIdentification = \
        apps.get_model('main', 'StandardizedIdentification')

    # remove identifiers that don't point to anything
    StandardizedIdentification.objects.filter(
        person=None, writtenwork=None, imprint=None).delete()

    # trim identifiers that have leading or trailing spaces
    for si in StandardizedIdentification.objects.all():
        si.identifier = si.identifier.strip()
        si.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20200610_2006'),
    ]

    operations = [
        migrations.RunPython(cleanup_standardized_identifiers),
    ]
