# Generated by Django 2.2.15 on 2020-08-21 14:31

from django.db import migrations

from footprints.main.models import SLUG_BHB


def cleanup_bhb_numbers(apps, schema_editor):
    StandardizedIdentification = \
        apps.get_model('main', 'StandardizedIdentification')

    # prepend leading zeroes onto identifiers that are < 9 characters
    qs = StandardizedIdentification.objects.filter(
        identifier_type__slug=SLUG_BHB)

    for si in qs:
        if len(si.identifier) < 9:
            si.identifier = si.identifier.rjust(9, '0')
            si.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20200821_1007'),
    ]

    operations = [
        migrations.RunPython(cleanup_bhb_numbers),
    ]
