# Generated by Django 2.2.15 on 2020-08-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20200821_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='marc_code',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
