# Generated by Django 2.2.17 on 2021-01-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_imprintalternatetitle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('canonical_place', 'alternate_name')},
        ),
    ]
