# Generated by Django 4.2.16 on 2024-11-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalobject',
            name='alt_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
