# Generated by Django 6.1.1 on 2026-09-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_digitalobject_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeddate',
            name='earliest_date',
            field=models.DateField(editable=False, null=True),
        ),
    ]
