# Generated by Django 6.1.1 on 2026-09-16 20:31

from datetime import date
from django.db import migrations
from edtf.edtf import EDTF


def calculate_earliest(value):
    edtf = EDTF(value)

    if edtf.is_interval:
        dt = edtf.start_date_earliest()
    else:
        dt = edtf.date_earliest()

    # Matches ExtendedDate._validate_python_date().
    return None if not dt or dt.year == date.max.year else dt


def backfill_earliest_date(apps, schema_editor):
    ExtendedDate = apps.get_model("main", "ExtendedDate")
    manager = ExtendedDate.objects.using(
        schema_editor.connection.alias
    )

    batch = []

    for obj in manager.only("pk", "edtf_format").iterator(chunk_size=500):
        try:
            obj.earliest_date = calculate_earliest(obj.edtf_format)
        except Exception as exc:
            raise ValueError(
                "Cannot parse ExtendedDate pk={} value={!r}".format(
                    obj.pk, obj.edtf_format
                )
            ) from exc

        batch.append(obj)

        if len(batch) == 500:
            manager.bulk_update(batch, ["earliest_date"], batch_size=500)
            batch = []

    if batch:
        manager.bulk_update(batch, ["earliest_date"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_extendeddate_earliest_date'),
    ]

    operations = [
        migrations.RunPython(
            backfill_earliest_date,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
