# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-28 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
